# Seed records give the frontend and API realistic demo data before a database exists.
PROJECTS = [
    {
        "id": "proj-retail-atl",
        "name": "Atlanta Retail Expansion",
        "tenant_id": "tenant-torilaure",
        "project_type": "retail-intelligence",
        "owner": "Analyst Ops",
        "owner_id": "user-analyst-demo",
        "member_ids": ["user-ravi-kafley", "user-analyst-demo"],
        "status": "active",
        "active_deals": 18,
        "stage": "underwriting",
        "investment_thesis": "Acquire overlooked neighborhood retail with steady rent growth and low capex needs.",
        "target_irr": 17.5,
        "budget_amount": 8400000,
    },
    {
        "id": "proj-roi-sunbelt",
        "name": "Sunbelt Deal Pipeline",
        "tenant_id": "tenant-torilaure",
        "project_type": "investment-roi",
        "owner": "Growth Capital",
        "owner_id": "user-ravi-kafley",
        "member_ids": ["user-ravi-kafley", "user-analyst-demo", "user-investor-demo"],
        "status": "monitoring",
        "active_deals": 42,
        "stage": "screening",
        "investment_thesis": "Prioritize Sunbelt opportunities where pricing has softened faster than NOI expectations.",
        "target_irr": 20.0,
        "budget_amount": 15000000,
    },
    {
        "id": "proj-northstar-ops",
        "name": "Northstar Operations Review",
        "tenant_id": "tenant-northstar",
        "project_type": "business-analysis",
        "owner": "Northstar Capital",
        "owner_id": "user-northstar-admin",
        "member_ids": ["user-northstar-admin"],
        "status": "active",
        "active_deals": 6,
        "stage": "portfolio-review",
        "investment_thesis": "Review portfolio efficiency before launching a new acquisition cycle.",
        "target_irr": 14.0,
        "budget_amount": 5000000,
    },
]

# Listings model the investment opportunities that feed ROI analysis and ranking.
LISTINGS = [
    {
        "id": "deal-1001",
        "tenant_id": "tenant-torilaure",
        "project_id": "proj-roi-sunbelt",
        "title": "Charlotte Multifamily Portfolio",
        "asset_class": "real-estate",
        "location": "Charlotte, NC",
        "asking_price": 6200000,
        "projected_irr": 18.6,
        "deal_score": 91,
        "summary": "Stable occupancy with upside through operational improvements.",
        "risk_level": "medium",
        "occupancy_rate": 95.4,
        "hold_period_months": 60,
        "status": "screening",
    },
    {
        "id": "deal-1002",
        "tenant_id": "tenant-torilaure",
        "project_id": "proj-roi-sunbelt",
        "title": "Houston Auto Service Franchise",
        "asset_class": "franchise",
        "location": "Houston, TX",
        "asking_price": 1480000,
        "projected_irr": 22.1,
        "deal_score": 88,
        "summary": "High-margin unit economics with favorable demographic growth.",
        "risk_level": "medium",
        "occupancy_rate": None,
        "hold_period_months": 48,
        "status": "pipeline",
    },
    {
        "id": "deal-1003",
        "tenant_id": "tenant-torilaure",
        "project_id": "proj-retail-atl",
        "title": "Nashville Specialty Manufacturing",
        "asset_class": "business",
        "location": "Nashville, TN",
        "asking_price": 3950000,
        "projected_irr": 16.2,
        "deal_score": 79,
        "summary": "Strong cash conversion with moderate supplier concentration risk.",
        "risk_level": "high",
        "occupancy_rate": None,
        "hold_period_months": 72,
        "status": "underwriting",
    },
]

# Market insights mimic enrichment signals that would later come from external data pipelines.
MARKET_INSIGHTS = [
    {
        "id": "insight-southeast",
        "tenant_id": "tenant-torilaure",
        "region": "Southeast",
        "signal": "Rent growth stays above inflation in secondary metros.",
        "trend": "up",
        "confidence": 0.82,
        "source": "market-research",
        "as_of_date": "2026-03-01",
    },
    {
        "id": "insight-texas",
        "tenant_id": "tenant-torilaure",
        "region": "Texas",
        "signal": "Franchise traffic remains resilient despite wage pressure.",
        "trend": "stable",
        "confidence": 0.76,
        "source": "operations-benchmarking",
        "as_of_date": "2026-03-03",
    },
    {
        "id": "insight-midsouth",
        "tenant_id": "tenant-torilaure",
        "region": "Mid-South",
        "signal": "Industrial demand softens, favoring disciplined capex scenarios.",
        "trend": "down",
        "confidence": 0.68,
        "source": "internal-research",
        "as_of_date": "2026-03-05",
    },
]

# Alert preferences represent user-configured notification rules.
ALERTS = [
    {
        "id": "alert-1",
        "tenant_id": "tenant-torilaure",
        "name": "High-score listings",
        "channel": "email",
        "trigger": "deal_score >= 85",
        "enabled": True,
        "scope": "tenant",
        "severity": "high",
    },
    {
        "id": "alert-2",
        "tenant_id": "tenant-torilaure",
        "name": "Market shock watch",
        "channel": "slack",
        "trigger": "regional_demand_delta <= -10%",
        "enabled": True,
        "scope": "tenant",
        "severity": "critical",
    },
]
