# Seed records give the frontend and API realistic demo data before a database exists.
PROJECTS = [
    {
        "id": "proj-retail-atl",
        "name": "Atlanta Retail Expansion",
        "tenant_id": "tenant-torilaure",
        "project_type": "retail-intelligence",
        "owner": "Analyst Ops",
        "owner_id": "user-analyst-demo",
        "member_ids": ["user-ravi-kafley", "user-analyst-demo"],
        "status": "active",
        "active_deals": 18,
        "stage": "underwriting",
        "investment_thesis": "Acquire overlooked neighborhood retail with steady rent growth and low capex needs.",
        "target_irr": 17.5,
        "budget_amount": 8400000,
    },
    {
        "id": "proj-roi-sunbelt",
        "name": "Sunbelt Deal Pipeline",
        "tenant_id": "tenant-torilaure",
        "project_type": "investment-roi",
        "owner": "Growth Capital",
        "owner_id": "user-ravi-kafley",
        "member_ids": ["user-ravi-kafley", "user-analyst-demo", "user-investor-demo"],
        "status": "monitoring",
        "active_deals": 42,
        "stage": "screening",
        "investment_thesis": "Prioritize Sunbelt opportunities where pricing has softened faster than NOI expectations.",
        "target_irr": 20.0,
        "budget_amount": 15000000,
    },
    {
        "id": "proj-northstar-ops",
        "name": "Northstar Operations Review",
        "tenant_id": "tenant-northstar",
        "project_type": "business-analysis",
        "owner": "Northstar Capital",
        "owner_id": "user-northstar-admin",
        "member_ids": ["user-northstar-admin"],
        "status": "active",
        "active_deals": 6,
        "stage": "portfolio-review",
        "investment_thesis": "Review portfolio efficiency before launching a new acquisition cycle.",
        "target_irr": 14.0,
        "budget_amount": 5000000,
    },
]

# Listings model the investment opportunities that feed ROI analysis and ranking.
LISTINGS = [
    {
        "id": "deal-1001",
        "tenant_id": "tenant-torilaure",
        "project_id": "proj-roi-sunbelt",
        "title": "Charlotte Multifamily Portfolio",
        "asset_class": "real-estate",
        "location": "Charlotte, NC",
        "asking_price": 6200000,
        "projected_irr": 18.6,
        "deal_score": 91,
        "summary": "Stable occupancy with upside through operational improvements.",
        "risk_level": "medium",
        "occupancy_rate": 95.4,
        "hold_period_months": 60,
        "status": "screening",
    },
    {
        "id": "deal-1002",
        "tenant_id": "tenant-torilaure",
        "project_id": "proj-roi-sunbelt",
        "title": "Houston Auto Service Franchise",
        "asset_class": "franchise",
        "location": "Houston, TX",
        "asking_price": 1480000,
        "projected_irr": 22.1,
        "deal_score": 88,
        "summary": "High-margin unit economics with favorable demographic growth.",
        "risk_level": "medium",
        "occupancy_rate": None,
        "hold_period_months": 48,
        "status": "pipeline",
    },
    {
        "id": "deal-1003",
        "tenant_id": "tenant-torilaure",
        "project_id": "proj-retail-atl",
        "title": "Nashville Specialty Manufacturing",
        "asset_class": "business",
        "location": "Nashville, TN",
        "asking_price": 3950000,
        "projected_irr": 16.2,
        "deal_score": 79,
        "summary": "Strong cash conversion with moderate supplier concentration risk.",
        "risk_level": "high",
        "occupancy_rate": None,
        "hold_period_months": 72,
        "status": "underwriting",
    },
]

# Market insights mimic enrichment signals that would later come from external data pipelines.
MARKET_INSIGHTS = [
    {
        "id": "insight-southeast",
        "tenant_id": "tenant-torilaure",
        "region": "Southeast",
        "signal": "Rent growth stays above inflation in secondary metros.",
        "trend": "up",
        "confidence": 0.82,
        "source": "market-research",
        "as_of_date": "2026-03-01",
    },
    {
        "id": "insight-texas",
        "tenant_id": "tenant-torilaure",
        "region": "Texas",
        "signal": "Franchise traffic remains resilient despite wage pressure.",
        "trend": "stable",
        "confidence": 0.76,
        "source": "operations-benchmarking",
        "as_of_date": "2026-03-03",
    },
    {
        "id": "insight-midsouth",
        "tenant_id": "tenant-torilaure",
        "region": "Mid-South",
        "signal": "Industrial demand softens, favoring disciplined capex scenarios.",
        "trend": "down",
        "confidence": 0.68,
        "source": "internal-research",
        "as_of_date": "2026-03-05",
    },
]

# Alert preferences represent user-configured notification rules.
ALERTS = [
    {
        "id": "alert-1",
        "tenant_id": "tenant-torilaure",
        "name": "High-score listings",
        "channel": "email",
        "trigger": "deal_score >= 85",
        "enabled": True,
        "scope": "tenant",
        "severity": "high",
    },
    {
        "id": "alert-2",
        "tenant_id": "tenant-torilaure",
        "name": "Market shock watch",
        "channel": "slack",
        "trigger": "regional_demand_delta <= -10%",
        "enabled": True,
        "scope": "tenant",
        "severity": "critical",
    },
]

ROI_SCENARIOS = [
    {
        "id": "roi-base-sunbelt",
        "project_id": "proj-roi-sunbelt",
        "tenant_id": "tenant-torilaure",
        "listing_id": "deal-1001",
        "name": "Base case",
        "scenario_type": "base",
        "lease_assumptions": [],
        "purchase_price": 6200000,
        "upfront_capex": 450000,
        "annual_revenue": 980000,
        "vacancy_rate": 5.0,
        "annual_operating_expenses": 320000,
        "annual_capex_reserve": 45000,
        "annual_revenue_growth_rate": 3.0,
        "annual_expense_growth_rate": 2.0,
        "exit_cap_rate": 6.5,
        "exit_cost_rate": 2.0,
        "hold_period_years": 5,
        "discount_rate": 12.0,
        "leverage_ratio": 55.0,
        "interest_rate": 6.0,
        "interest_only_years": 1,
        "amortization_period_years": 30,
        "net_operating_income": 660000,
        "terminal_value": 11199153.85,
        "total_profit": 5111722.31,
        "equity_invested": 3240000,
        "debt_amount": 3410000,
        "ending_loan_balance": 2945000,
        "sale_proceeds_after_debt": 8021170.77,
        "average_annual_cash_flow": 1674344.46,
        "projected_irr": 25.27,
        "projected_npv": 2485758.24,
        "unlevered_irr": 18.92,
        "unlevered_npv": 1764201.55,
        "cash_on_cash_multiple": 2.584,
        "equity_multiple": 2.584,
        "unlevered_equity_multiple": 1.944,
        "average_cash_on_cash_return": 13.84,
        "first_year_cash_on_cash_return": 11.91,
        "cap_rate_on_cost": 9.94,
        "average_dscr": 1.61,
        "minimum_dscr": 1.47,
        "payback_period_years": 2.83,
    },
    {
        "id": "roi-upside-sunbelt",
        "project_id": "proj-roi-sunbelt",
        "tenant_id": "tenant-torilaure",
        "listing_id": "deal-1001",
        "name": "Upside case",
        "scenario_type": "upside",
        "lease_assumptions": [],
        "purchase_price": 6200000,
        "upfront_capex": 400000,
        "annual_revenue": 1040000,
        "vacancy_rate": 4.0,
        "annual_operating_expenses": 315000,
        "annual_capex_reserve": 40000,
        "annual_revenue_growth_rate": 4.5,
        "annual_expense_growth_rate": 2.0,
        "exit_cap_rate": 6.0,
        "exit_cost_rate": 2.0,
        "hold_period_years": 5,
        "discount_rate": 12.0,
        "leverage_ratio": 55.0,
        "interest_rate": 6.0,
        "interest_only_years": 1,
        "amortization_period_years": 30,
        "net_operating_income": 725000,
        "terminal_value": 13622523.39,
        "total_profit": 7411430.58,
        "equity_invested": 3190000,
        "debt_amount": 3410000,
        "ending_loan_balance": 2945000,
        "sale_proceeds_after_debt": 10464880.91,
        "average_annual_cash_flow": 2126086.12,
        "projected_irr": 34.67,
        "projected_npv": 4292630.84,
        "unlevered_irr": 24.16,
        "unlevered_npv": 3021140.26,
        "cash_on_cash_multiple": 3.333,
        "equity_multiple": 3.333,
        "unlevered_equity_multiple": 2.281,
        "average_cash_on_cash_return": 18.72,
        "first_year_cash_on_cash_return": 15.36,
        "cap_rate_on_cost": 10.97,
        "average_dscr": 1.88,
        "minimum_dscr": 1.69,
        "payback_period_years": 2.19,
    },
    {
        "id": "roi-downside-sunbelt",
        "project_id": "proj-roi-sunbelt",
        "tenant_id": "tenant-torilaure",
        "listing_id": "deal-1001",
        "name": "Downside case",
        "scenario_type": "downside",
        "lease_assumptions": [],
        "purchase_price": 6200000,
        "upfront_capex": 600000,
        "annual_revenue": 910000,
        "vacancy_rate": 8.0,
        "annual_operating_expenses": 345000,
        "annual_capex_reserve": 65000,
        "annual_revenue_growth_rate": 1.0,
        "annual_expense_growth_rate": 3.5,
        "exit_cap_rate": 7.25,
        "exit_cost_rate": 2.0,
        "hold_period_years": 5,
        "discount_rate": 12.0,
        "leverage_ratio": 55.0,
        "interest_rate": 6.0,
        "interest_only_years": 1,
        "amortization_period_years": 30,
        "net_operating_income": 565000,
        "terminal_value": 7748294.24,
        "total_profit": 1778294.69,
        "equity_invested": 3390000,
        "debt_amount": 3410000,
        "ending_loan_balance": 2945000,
        "sale_proceeds_after_debt": 4643328.36,
        "average_annual_cash_flow": 1035658.94,
        "projected_irr": 13.77,
        "projected_npv": 360908.73,
        "unlevered_irr": 9.84,
        "unlevered_npv": 228551.14,
        "cash_on_cash_multiple": 1.529,
        "equity_multiple": 1.529,
        "unlevered_equity_multiple": 1.311,
        "average_cash_on_cash_return": 7.42,
        "first_year_cash_on_cash_return": 4.93,
        "cap_rate_on_cost": 8.35,
        "average_dscr": 1.21,
        "minimum_dscr": 1.08,
        "payback_period_years": 4.02,
    },
]
